# Opencv入门

## 2.1 读图、展示和保存新图

In [1]:
import cv2 as cv

In [2]:
# 简单传入图像存放地址，返回一个代表图像的Numpy数组
image = cv.imread('./songyi.jpg')

* cv.imread()存在第二个参数，表示图片的返回方式
* cv.IMREAD_COLOR,cv.IMREAD_GRAYSCALE,cv.IMREAD_UNCHANGED表示读取彩色图片，灰度图片，不变读取图片
* 也可以使用数字-1,0,1表示上述参数

In [4]:
print("width:{} pixels".format(image.shape[1]))
print("height:{} pixels".format(image.shape[0]))
print("channels:{} ".format(image.shape[2]))

width:2048 pixels
height:1400 pixels
channels:3 


* OPENCV读取图片的数据格式为H*W*C即高度，宽度，通道数
* 通道顺序为BGR

In [5]:
# 显示图片,第一个参数表示窗口显示的字符串，第二个参数表示显示的图像数据
cv.imshow("songyi",image)
cv.waitKey(0)

-1

In [6]:
# 保存图像数据
cv.imwrite("songyi.png",image)

True

## 2.2 像素点和局部图像

* 图像数据以左上角为原点即(0,0)，向右向下为正

* 可以使用python切片方式获取局部像素值

In [7]:
patch1 = image[100:500,1000:1500]
cv.imshow("patch1",patch1)
cv.waitKey(0)

-1

## 2.3 基本线条操作

* OPENCV提供了基本的线条操作，包括画线，画矩形等

In [8]:
import numpy as np

# 生成一个300*300大小的全黑画板
canvas = np.zeros((300,300,3),dtype = 'uint8')

for _ in range(25):
    # 随机生成一个半径值
    radius = np.random.randint(5,200)
    # 随机生成一个填充的颜色
    color = np.random.randint(0,256,size = (3,)).tolist()
    # 圆中心坐标值
    pt = np.random.randint(0,200,size = (2,))
    
    # 画圆操作，canvas表示操作的图像，pt表示圆的中心坐标，radius表示圆的半径，color表示填充的颜色
    cv.circle(canvas,tuple(pt),radius,color,-1)
cv.imshow("canvas",canvas)
cv.waitKey(0)

-1

In [10]:
# 生成一个300*300大小的全黑画板
canvas = np.zeros((300,300,3),dtype = 'uint8')

for _ in range(25):
    # 随机生成一个填充的颜色
    color = np.random.randint(0,256,size = (3,)).tolist()
    # 圆中心坐标值
    pt1 = np.random.randint(0,200,size = (2,))
    pt2 = np.random.randint(0,200,size = (2,))
    
    # 画矩形框,pt1,pt2表示矩形框的对角坐标，color表示使用的颜色，thickness为负值时表示填充整个矩形框，为正值时表示矩形框的线框
    cv.rectangle(canvas,pt1,pt2,color,thickness = 1)
cv.imshow("canvas",canvas)
cv.waitKey(0)

-1

In [14]:
canvas = np.zeros((300,300,3),dtype = 'uint8')
text = 'Hello World'
color1 = np.random.randint(0,256,size = (3,)).tolist()
color2 = np.random.randint(0,256,size = (3,)).tolist()
pt1 = (100,100)
pt2 = (250,250)
cv.rectangle(canvas,pt1,pt2,color1,thickness = 1)
cv.putText(canvas,text,pt1,cv.FONT_HERSHEY_SIMPLEX,1,color = color2)
cv.imshow("canvas",canvas)
cv.waitKey(0)

-1

## 2.4 平移

* 平移就是将图片进行移动，主要参数为含方向和距离的平移矩阵

In [3]:
import numpy as np

M = np.float32([[1,0,25],[0,1,50]])
shift_image = cv.warpAffine(image,M,(image.shape[1],image.shape[0]))
cv.imshow("shift_image",shift_image)
cv.waitKey(0)

-1

## 2.5旋转矩阵

In [6]:
(h,w) = image.shape[:2]

center = (w //2,h//2)

# 构建旋转矩阵,center表示旋转固定点，135表示旋转角度，1.0表示图片缩放尺度
M = cv.getRotationMatrix2D(center,135,1.0)
Rotated_image = cv.warpAffine(image,M,(w,h))
cv.imshow("Rotated image",Rotated_image)
cv.waitKey(0)

-1

## 2.6 缩放

* cv.resize()主要有三个参数，第一个参数为缩放图像，第二个参数为缩放尺寸，第三个参数为插值选项

In [7]:
resize_image = cv.resize(image,(500,500))
cv.imshow("resize_image",resize_image)
cv.waitKey(0)

-1

## 2.7 翻转

* cv.flip()第二个参数1表示水平翻转，0表示垂直翻转，-1表示水平和垂直翻转

In [4]:
v_image = cv.flip(image,0)
h_image = cv.flip(image,1)
vh_image = cv.flip(image,-1)

cv.imshow("v_image",v_image)
cv.waitKey(0)
cv.imshow("h_image",h_image)
cv.waitKey(0)
cv.imshow("vh_image",vh_image)
cv.waitKey(0)

-1

## 2.8 裁剪

* 使用numpy切片操作即可

## 2.9 算术操作

In [5]:
x,y = np.uint8([100]),np.uint8([200])
x,y

(array([100], dtype=uint8), array([200], dtype=uint8))

In [6]:
cv.add(x,y) # 最大值为255，采取截断策略

array([[255]], dtype=uint8)

In [7]:
cv.subtract(x,y)

array([[0]], dtype=uint8)

In [8]:
x+y # numpy采取取模操作

array([44], dtype=uint8)

In [9]:
x-y # 100-200+156

array([156], dtype=uint8)

## 2.10 位操作

* 位操作是在灰度图像像素级别的布尔运算

In [10]:
rectangle = np.zeros((100,100),dtype = "uint8")
cv.rectangle(rectangle,(30,30),(70,70),255,-1)
cv.imshow("Rectangle",rectangle)

circle = np.zeros((100,100),dtype = "uint8")
cv.circle(circle,(50,50),25,255,-1)
cv.imshow("circle",circle)

bitwiseAnd = cv.bitwise_and(rectangle,circle)
cv.imshow("and",bitwiseAnd)

bitwiseOr = cv.bitwise_or(rectangle,circle)
cv.imshow("OR",bitwiseOr)

bitwiseXor = cv.bitwise_xor(rectangle,circle)
cv.imshow("XOR",bitwiseXor)

bitwiseNot = cv.bitwise_not(rectangle,circle)
cv.imshow("NOT",bitwiseNot)

cv.waitKey(0)


-1